---
title: "Severe Weather and Natural Hazard Assessment"
author: "vpipkt"
date: "Sunday, February 15, 2015"
output: html_document
---

##Synopsis
desscribes and summarizes your analysis in at most 10 complete sentences.

##Data Processing
The United States National Weather Service (NWS) publishes the *Storm Data* publication and database. It is a record of severe weather and natural hazard events with measurements and narratives. The Coursera web site provides this data from 1950 to 2011. The first step of data processing is to unzip and read in the data. Given the summary nature of the questions at hand, only selected fields are carefully cleaned for further analysis.  Of part

```{r unzip,cache=TRUE}
storm.data <- read.csv(bzfile("repdata-data-StormData.csv.bz2"),colClasses="character")
nrow(storm.data)

storm.data$BGN_DATE <- as.POSIXct(storm.data$BGN_DATE, "%m/%d/%Y %H:%M:%S")
storm.data$STATE <- as.factor(storm.data$STATE)
storm.data$EVTYPE <- as.factor(storm.data$EVTYPE)
levels(storm.data$EVTYPE)
storm.data$FATALITIES <- as.numeric(storm.data$FATALITIES)
storm.data$INJURIES <- as.numeric(storm.data$INJURIES)
storm.data$PROPDMG <- as.numeric(storm.data$PROPDMG)
storm.data$PROPDMGEXP <- as.factor(storm.data$PROPDMGEXP)

summary(storm.data$PROPDMGEXP)

exponents <- data.frame(exp=c("B","h","H","K","m","M"),
                        mult=c(1e9,1e2,1e2,1e3,1e6,1e6))
storm.data <- merge(storm.data,exponents,by.x="PROPDMGEXP", by.y="exp",all.x=T)
storm.data$PropertyDamage <- storm.data$PROPDMG * storm.data$mult

```


 
##Results
Contains results and at least 1 but no more than 3 Figures
 



##Questions

1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

1. Across the United States, which types of events have the greatest economic consequences?




The chosen measure of public health outcomes is the total of direct fatalities over the period. As stated in section 2.6 of the National Weather Service Instruction 10-1605: "The determination of direct versus indirect causes of weather-related fatalities or injuries is one of the most difficult aspects of Storm Data preparation."  Also consider that reporting of injuries may be less reliable than reporting of fatalities, which is a standard public health record. Further, comparison of injuries is dubious at best. An injury may result in a wide range of outcomes from temporary inconvenience, costly medical intervention, or permanent disability. 


Property damage estimates vary by method of preparation, preparer and data sources. This is clearly described in the National Weather Service Instruction. These estimates are characterized by the NWS as a [best guess](http://). 